target_link_libraries(
     SlideProjector
        glad
        glfw3
        pthread
        dl
        X11
        freeimage
        opencv_core
        opencv_imgproc
        opencv_imgcodecs
        opencv_videoio
)